name: Greeting
on: [workflow_dispatch]
#below is the expanded version
# on:
#   - push
#   - workflow_dispatch
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: "Grret the World"
        run: echo "Hello, World!"
